# Generated by Django 5.2.16 on 2026-07-22 01:12

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Equip",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "deleted_at",
                    models.DateTimeField(
                        blank=True,
                        default=None,
                        editable=False,
                        null=True,
                        verbose_name="deleted date",
                    ),
                ),
                ("name", models.CharField(max_length=100)),
                ("locate", models.CharField(max_length=100)),
                ("ipaddress", models.GenericIPAddressField(default=0)),
                ("etc", models.CharField(blank=True, max_length=300, null=True)),
            ],
            options={
                "abstract": False,
            },
        ),
    ]
